### ISSUE TITLE
Error after adding repo

### ISSUE THREAD

**Issue by timkopperud** [troykelly/hassio-addons-letsencrypt-lexicon#1]
I get this error when trying to add this repository.

20-01-12 12:48:05 ERROR (MainThread) [hassio.utils.json] Can't read json from /data/addons/git/adcd40ea/repository.json: [Errno 2] No such file or directory: '/data/addons/git/adcd40ea/repository.json'

The repo is listed as unknown, and there are no add-ons shown from this repo.

Any tips for this? Thanks.

**Comment by troykelly** [comment]
Apologies @timkopperud 
The documentation is incorrect - whilst this is the repo for the addon - the repository for them is troykelly/hassio-addons.

I've updated the documentation - please let me know if you have an issue.

## Installation

The installation of these add-ons is straightforward and easy to do.

1. Navigate in your Home Assistant frontend to **Hass.io** -> **Add-on Store**.
2. Add a new repository by URL `https://github.com/troykelly/hassio-addons`
3. Find the add-on you need and click it.
4. Click on the "INSTALL" button.

**Comment by timkopperud** [comment]
Thanks for swift reply. Now I get the addons listed. When trying to install I get this error:

20-01-12 22:01:09 ERROR (SyncWorker_8) [hassio.docker.interface] Can't install troykelly/armv7-addon-letslexicon:1.0.0 -> 404 Client Error: Not Found ("manifest for troykelly/armv7-addon-letslexicon:1.0.0 not found")

Thanks.

**Comment by troykelly** [comment]
Okay @timkopperud that's annoying - that armv7 version mustn't be succeeding and uploading.
I will have to look tonight after day-job.

**Comment by troykelly** [comment]
@timkopperud I've redone all the images - can you please let me know if it's still not working?

**Comment by timkopperud** [comment]
Thanks. Still get this error after reinstalling the addon repo:

20-01-14 08:07:48 INFO (SyncWorker_0) [hassio.docker.interface] Pull image troykelly/armv7-addon-letslexicon tag 1.0.0.
20-01-14 08:07:49 ERROR (SyncWorker_0) [hassio.docker.interface] Can't install troykelly/armv7-addon-letslexicon:1.0.0 -> 404 Client Error: Not Found ("manifest for troykelly/armv7-addon-letslexicon:1.0.0 not found").

**Comment by troykelly** [comment]
@timkopperud Looks like that Hassio builder when building "ALL" wasn't building the armv7 image that you need. I've bumped the version number and manually built the image:
```bash
docker run --rm --privileged homeassistant/amd64-builder --armv7 --docker-user ${DOCKER_USER} --docker-password "${DOCKER_PASSWORD}" -b master -r https://github.com/troykelly/hassio-addons-letsencrypt-lexicon
```
And it appears to be available:
```bash
Trying to pull docker.io/troykelly/armv7-addon-letslexicon:1.0.1...Getting image source signatures
Copying blob cf9b14211c5b done
Copying blob 81437315e2f2 done
Copying blob 983c1cbe8050 done
Copying blob f6ea62944378 done
Copying blob 3018dddc66b1 done
Copying blob 3922e475e500 done
Copying blob 0efc75d1f7d1 done
Copying blob 266641e0066d done
Copying blob 661ba8f10a34 done
Copying blob 2cbe3acdd210 done
Copying config 993c34494d done
Writing manifest to image destination
Storing signatures
993c34494dfd90dd498174c9a2b71cfa4323306f6d9c6c9235ce8749bfc1542d
```
Hopefully, that fixes the problem you are having. I've still got to work out what is causing #2 but this will at least get your certs working.

**Comment by timkopperud** [comment]
Yes. That solved it. Successfully installed the addon. Thanks for swift support. Great.
Thanks again.

**Comment by troykelly** [comment]
Great to hear @timkopperud 
Closing.

**Comment by xvolte** [comment]
@troykelly can we reopen ?
When i try to add the repository : 
![image](https://user-images.githubusercontent.com/21142611/99829607-ce1e2600-2b5c-11eb-9c1c-d312552b0477.png)

This does not allow me to add it : 

`Repostitory structure for master is not compliant`

**Comment by troykelly** [comment]
@xvolte Can you confirm that you are adding `https://github.com/troykelly/hassio-addons`?
I've just tested on both my HA instances and I can remove and re-add it.

**Comment by xvolte** [comment]
> @xvolte Can you confirm that you are adding `https://github.com/troykelly/hassio-addons`?
> I've just tested on both my HA instances and I can remove and re-add it.

Yes that is the link i'm using. and it's not working, even after a reboot.

What is your HA version ?

My config: 

- arch | armv7l
- chassis | embedded
- dev | false
- docker | true
- docker_version | 19.03.11
- hassio | true
- host_os | HassOS 4.13
- installation_type | Home Assistant OS
- os_name | Linux
- os_version | 4.19.127-v7
- python_version | 3.8.5
- supervisor | 2020.11.0
- timezone | Europe/Paris
- version | 0.116.4
- virtualenv | false

**Comment by troykelly** [comment]
@xvolte It looks like you are trying to add this to HACS? This is a docker addon, not a HACS plugin, unfortunately.
Make sure you are adding to the Supervisor add on store.
I've just run up a VM matching your version - and it seems to be able to add successfully.
https://youtu.be/xLKTOYpmiF4
<img width="1355" alt="Screen Shot 2020-11-21 at 10 34 42 pm" src="https://user-images.githubusercontent.com/4564803/99876282-d902b480-2c49-11eb-916b-4836d5a948af.png">

**Comment by xvolte** [comment]
haaaaaaaa got it !

Really sorry for the confusion, you are right. maybe be even more clear in the Readme for others :) (but my mistake :))
