### ISSUE TITLE
Terms Accept problem...

### ISSUE THREAD

**Issue by Sany-IO** [troykelly/hassio-addons-letsencrypt-lexicon#27]
# INFO: Using main config file /etc/dehydrated/config
To use dehydrated with this certificate authority you have to agree to their terms of service which you can find here: https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf
To accept these terms of service run `/opt/dehydrated/dehydrated --register --accept-terms`.
[20:33:57] WARNING: certificate refresh crashed, halting add-on

how can i fix this error?

**Comment by troykelly** [comment]
It sounds like there could be an issue with your certificate store, perhaps a full disk?
I'm not sure what the best course of action would be.
You could try backing up the contents of the `ssl` directory, emptying it - and restarting the add-on.
You will need a tool to access your install - something like [Terminal & SSH](https://github.com/home-assistant/addons/tree/master/ssh)

## Danger
Make sure you only delete the contents of `ssl` if you follow the below

```bash
➜  ~ cd config
➜  config tar zcvf ./ssl-backup.tgz ../ssl 
a ../ssl
a ../ssl/privkey.pem
a ../ssl/example_com
a ../ssl/fullchain.pem
a ../ssl/example_com/privkey-1667609229.pem
a ../ssl/example_com/chain.pem
a ../ssl/example_com/chain-1667609229.pem
a ../ssl/example_com/cert.csr
a ../ssl/example_com/cert.pem
a ../ssl/example_com/privkey.pem
a ../ssl/example_com/cert-1667609229.csr
a ../ssl/example_com/fullchain.pem
a ../ssl/example_com/cert-1667609229.pem
a ../ssl/example_com/fullchain-1667609229.pem
➜  config cd ../ssl 
➜  ssl find . -name . -o -prune -exec rm -rf -- {} +
```

**Comment by troykelly** [comment]
Closing
