### ISSUE TITLE
PowerDNS usage explanation

### ISSUE THREAD

**Issue by dwd1** [troykelly/hassio-addons-letsencrypt-lexicon#29]
Hi,
pls help me, explain the powerdns usage parameters because its not documented.
I would like to use this addon with powerdns.
powerdns_auth_token:
powerdns_pdns_server:
powerdns_pdns_server_id:
powerdns_pdns_disable_notify:
Thank you!

**Comment by dwd1** [comment]
solved, thank you

**Comment by troykelly** [comment]
Hi there @dwd1,
I see you solved this - documentation is here
https://dns-lexicon.readthedocs.io/en/latest/configuration_reference.html#powerdns
