### ISSUE TITLE
[Feature] Godaddy api-ote 

### ISSUE THREAD

**Issue by ditheo** [troykelly/hassio-addons-letsencrypt-lexicon#44]
Since Godaddy has disable access to their api on users that have less than 10 domains and they have left only access to the test OTE api , could You add a godaddy ote dns support? I think i am not the only one that use their api for dns purposes... And probably many users will face problems with that , because there is no information on their site.

Thank you 

Dimosthenis

**Comment by troykelly** [comment]
Hi there @ditheo.

As far as I know, the GoDaddy OTE is primarily a sandbox environment intended for testing and development purposes. It allows developers to test API interactions without affecting live data.

Can you please provide more information or clarify if the OTE can indeed be used to manage domains for users with fewer than 10 domains in a live setting? If there's any specific documentation or reference you have regarding this, it would be very helpful. This will ensure that we implement the feature correctly and it meets your needs.

It would need to be implemented in Lexicon before it could be added to this addon.

https://dns-lexicon.readthedocs.io/en/latest/configuration_reference.html#godaddy

**Comment by troykelly** [comment]
Closing this for now, let me know if you need anything else.
